#!/usr/bin/env python3
"""
synthesize.py — markdown report builder for ultrasearch (Stage 1).

Stage 1 scope (01_stage1.md §3.14 / research §6 line 99):
    - Build a structured markdown report from retrieved chunks.
    - Every cited statement carries an `[Sn]` marker.
    - A trailing `## References` section lists `[Sn]` → DOI/title/venue/year.
    - No LLM calls in Stage 1 — the report is deterministic: it stitches
      ranked chunk text under thematic headings derived from the chunks
      themselves. The orchestrator (or the user, via /ultrasearch) can pipe
      the output back through Claude for prose-quality polish in a separate
      step — that is Stage 3 (outline → section → polish via subagents).

Stage 3 will replace this with: outline → parallel section drafts (via
Claude subagents) → polish → CriticAgent validation.

Output structure:
    # <query — research brief>
    ## TL;DR
    <one-paragraph stitched abstract using top-3 hits>
    ## Findings
    ### <theme 1>
    ...para citing [S1] [S2]...
    ### <theme 2>
    ...
    ## Open questions
    <bullets derived from hit titles that diverge>
    ## References
    - [S1] <doi or arxiv:id> — <title>, <authors>, <venue> <year>.
    - [S2] ...
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from typing import Any, Iterable

from _common import emit_failure, json_stdout, log, normalize_doi
from retrieve import Hit


MAX_CHUNK_CHARS = 800            # truncate each cited chunk for the body
MAX_TOPN_FOR_TLDR = 3
MAX_FINDINGS_PARAS = 8
MAX_OPEN_QUESTIONS = 5


def _ref_label(idx: int) -> str:
    return f"S{idx + 1}"


def _ref_anchor(hit: Hit) -> str:
    """Identifier for the reference: prefer DOI, then arXiv id, then short
    title slug."""
    if hit.get("doi"):
        return hit["doi"]
    if hit.get("arxiv_id"):
        return f"arXiv:{hit['arxiv_id']}"
    return hit.get("title", "(untitled)")[:60]


def _ref_line(idx: int, hit: Hit,
              retraction_lookup: dict[str, dict[str, Any]] | None = None) -> str:
    authors = hit.get("authors") or []
    if authors:
        if len(authors) > 3:
            author_str = ", ".join(authors[:3]) + " et al."
        else:
            author_str = ", ".join(authors)
    else:
        author_str = "(unknown authors)"
    venue = hit.get("venue") or "(unknown venue)"
    year = hit.get("year") or "n.d."
    anchor = _ref_anchor(hit)
    title = (hit.get("title") or "(untitled)").strip()
    line = f"- [{_ref_label(idx)}] {anchor} — *{title}*, {author_str}, {venue}, {year}."
    # Stage 2: retraction footnote (research §6 line 99)
    if retraction_lookup:
        d = normalize_doi(hit.get("doi"))
        if d and d in retraction_lookup:
            rinfo = retraction_lookup[d]
            rd = rinfo.get("retraction_date") or "date unknown"
            reason = rinfo.get("reason") or "no reason provided"
            line += f" **⚠ RETRACTED ({rd}): {reason}**"
    return line


def _truncate(text: str, n: int) -> str:
    s = re.sub(r"\s+", " ", text).strip()
    if len(s) <= n:
        return s
    return s[: n - 1].rstrip() + "…"


def _group_by_paper(hits: list[Hit]) -> dict[str, list[Hit]]:
    by_pid: dict[str, list[Hit]] = {}
    for h in hits:
        by_pid.setdefault(h["paper_id"], []).append(h)
    return by_pid


def _dedup_hits(hits: list[Hit]) -> list[Hit]:
    """One hit per paper; keep the lowest-distance chunk per paper."""
    by_pid = _group_by_paper(hits)
    out: list[Hit] = []
    for pid, group in by_pid.items():
        group.sort(key=lambda h: h.get("distance", 1.0))
        out.append(group[0])
    out.sort(key=lambda h: h.get("distance", 1.0))
    return out


def synthesize(query: str, hits: list[Hit], *,
               retraction_lookup: dict[str, dict[str, Any]] | None = None,
               traversal_candidates: list[dict[str, Any]] | None = None) -> str:
    """Build the markdown report. Deterministic — no LLM calls.

    Stage 2 optional inputs:
      retraction_lookup: {normalized_doi: {retraction_date, reason}} — adds
          footnote markers on retracted entries in the References section.
      traversal_candidates: output of traverse.traverse_citations()["candidates"]
          — used to populate the "Open Questions / Related Directions" section
          with papers we found via citation snowballing but didn't index.
    """
    if not hits:
        return _empty_report(query)

    hits = _dedup_hits(hits)
    n_total = len(hits)

    lines: list[str] = []
    lines.append(f"# {query} — research brief")
    lines.append("")
    lines.append(f"*Auto-generated by ultrasearch (Stage 1) from {n_total} retrieved "
                 f"chunks. Each citation `[Sn]` resolves to a DOI/arXiv ID in the "
                 f"References section below.*")
    lines.append("")

    # TL;DR — stitch top 3
    lines.append("## TL;DR")
    lines.append("")
    tldr_parts: list[str] = []
    for i, h in enumerate(hits[:MAX_TOPN_FOR_TLDR]):
        snippet = _truncate(h["text"], 280)
        tldr_parts.append(f"{snippet} [{_ref_label(i)}]")
    lines.append(" ".join(tldr_parts))
    lines.append("")

    # Findings
    lines.append("## Findings")
    lines.append("")
    for i, h in enumerate(hits[:MAX_FINDINGS_PARAS]):
        title = (h.get("title") or "Untitled").strip()
        year = h.get("year") or ""
        venue = h.get("venue") or ""
        head_parts = [title]
        if year:
            head_parts.append(f"({year})")
        if venue:
            head_parts.append(f"— {venue}")
        lines.append(f"### {' '.join(head_parts)}")
        lines.append("")
        snippet = _truncate(h["text"], MAX_CHUNK_CHARS)
        lines.append(f"{snippet} [{_ref_label(i)}]")
        lines.append("")

    # Open questions — pull titles of lower-ranked hits that don't appear above
    open_section_started = False
    if len(hits) > MAX_FINDINGS_PARAS:
        rest = hits[MAX_FINDINGS_PARAS:MAX_FINDINGS_PARAS + MAX_OPEN_QUESTIONS]
        if rest:
            lines.append("## Open questions / related directions")
            lines.append("")
            open_section_started = True
            for i, h in enumerate(rest, start=MAX_FINDINGS_PARAS):
                title = (h.get("title") or "Untitled").strip()
                lines.append(f"- *{title}* — [{_ref_label(i)}]")
            lines.append("")

    # Stage 2: papers found via citation traversal but not yet indexed
    # (research §13 v0.5 — surface gaps as further-reading bullets)
    if traversal_candidates:
        if not open_section_started:
            lines.append("## Open questions / related directions")
            lines.append("")
        lines.append("**Discovered via citation graph traversal (not yet indexed):**")
        lines.append("")
        for c in traversal_candidates[:8]:
            title = (c.get("title") or "Untitled").strip()
            doi = c.get("doi") or c.get("arxiv_id") or ""
            direction = c.get("direction", "")
            arrow = "←" if direction == "backward" else "→"
            cit = f"[{doi}]" if doi else ""
            lines.append(f"- {arrow} *{title}* {cit}")
        lines.append("")

    # References
    lines.append("## References")
    lines.append("")
    for i, h in enumerate(hits):
        lines.append(_ref_line(i, h, retraction_lookup=retraction_lookup))
    lines.append("")

    return "\n".join(lines)


def _empty_report(query: str) -> str:
    return (
        f"# {query} — research brief\n\n"
        "*ultrasearch returned no candidate papers for this query. Possible "
        "causes:*\n"
        "- discovery sources rate-limited (re-run later)\n"
        "- query too narrow (broaden keywords)\n"
        "- non-English query without a Russian source enabled (Stage 3)\n\n"
        "Run with `--max-per-source 100` to widen the search and check the "
        "stderr log for per-source warnings.\n"
    )


def validate_report(md: str) -> dict[str, Any]:
    """Sanity-check the generated report. Returns:
        {"ok": True/False, "issues": [...]}
    Issues: paragraphs without citations, citation markers without References
    entries, References entries without citations in body.
    """
    issues: list[str] = []

    # Split body / References
    if "## References" in md:
        body, refs = md.split("## References", 1)
    else:
        body, refs = md, ""

    body_markers = set(re.findall(r"\[(S\d+)\]", body))
    ref_markers = set(re.findall(r"\[(S\d+)\]", refs))

    missing_refs = body_markers - ref_markers
    if missing_refs:
        issues.append(f"citation markers without References entries: {sorted(missing_refs)}")
    unused_refs = ref_markers - body_markers
    if unused_refs:
        issues.append(f"References entries not cited in body: {sorted(unused_refs)}")

    # paragraphs lacking any citation. Walk the body, ignore code blocks /
    # headings / TL;DR overall section (always cites). Treat empty body as OK.
    para_no_cite = 0
    for para in re.split(r"\n\s*\n", body):
        para = para.strip()
        if not para:
            continue
        if para.startswith(("#", ">", "*", "-", "```", "|", "*")):
            continue
        if "[S" in para:
            continue
        # bare prose paragraph without citation
        para_no_cite += 1
    if para_no_cite > 0:
        issues.append(f"{para_no_cite} prose paragraph(s) without citation markers")

    return {"ok": not issues, "issues": issues,
            "n_body_markers": len(body_markers),
            "n_ref_entries": len(ref_markers)}


def main() -> int:
    parser = argparse.ArgumentParser(prog="synthesize.py",
                                     description="Build a markdown report from retrieved hits.")
    parser.add_argument("--query", required=True)
    parser.add_argument("--hits-json", default=None,
                        help="path to JSON file containing {'hits':[...]} — else stdin")
    parser.add_argument("--out", default=None,
                        help="write report to file (else stdout)")
    parser.add_argument("--json", action="store_true",
                        help="also emit validation JSON on stderr")
    args = parser.parse_args()

    if args.hits_json:
        try:
            data = json.loads(open(args.hits_json).read())
        except Exception as e:
            emit_failure(f"cannot read hits-json: {e}")
            return 2
    else:
        try:
            data = json.loads(sys.stdin.read())
        except Exception as e:
            emit_failure(f"cannot parse stdin as JSON: {e}")
            return 2
    hits = data.get("hits") or []
    md = synthesize(args.query, hits)

    if args.out:
        try:
            open(args.out, "w", encoding="utf-8").write(md)
        except OSError as e:
            emit_failure(f"cannot write report: {e}")
            return 1
    else:
        sys.stdout.write(md)

    if args.json:
        v = validate_report(md)
        log(f"validation: {json.dumps(v, ensure_ascii=False)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
